/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

function __extractDefault(module2) {
  return module2 && module2.__esModule && module2.default ? module2.default : module2;
}

(function patchRequireEsmDefault() {
  const __require = require;
  require = Object.assign((id) => {
    const module2 = __require(id) ?? {};
    return __extractDefault(module2);
  }, __require);
})()

"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// node_modules/obsidian-dev-utils/dist/lib/Debug.cjs
var require_Debug = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/Debug.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var Debug_exports = {};
    __export2(Debug_exports, {
      isDebug: () => isDebug
    });
    module2.exports = __toCommonJS2(Debug_exports);
    function isDebug() {
      return globalThis.DEBUG ?? false;
    }
  }
});

// node_modules/eventemitter3/index.js
var require_eventemitter3 = __commonJS({
  "node_modules/eventemitter3/index.js"(exports2, module2) {
    "use strict";
    var has = Object.prototype.hasOwnProperty;
    var prefix = "~";
    function Events() {
    }
    if (Object.create) {
      Events.prototype = /* @__PURE__ */ Object.create(null);
      if (!new Events().__proto__) prefix = false;
    }
    function EE(fn, context, once) {
      this.fn = fn;
      this.context = context;
      this.once = once || false;
    }
    function addListener(emitter, event, fn, context, once) {
      if (typeof fn !== "function") {
        throw new TypeError("The listener must be a function");
      }
      var listener = new EE(fn, context || emitter, once), evt = prefix ? prefix + event : event;
      if (!emitter._events[evt]) emitter._events[evt] = listener, emitter._eventsCount++;
      else if (!emitter._events[evt].fn) emitter._events[evt].push(listener);
      else emitter._events[evt] = [emitter._events[evt], listener];
      return emitter;
    }
    function clearEvent(emitter, evt) {
      if (--emitter._eventsCount === 0) emitter._events = new Events();
      else delete emitter._events[evt];
    }
    function EventEmitter() {
      this._events = new Events();
      this._eventsCount = 0;
    }
    EventEmitter.prototype.eventNames = function eventNames() {
      var names = [], events, name;
      if (this._eventsCount === 0) return names;
      for (name in events = this._events) {
        if (has.call(events, name)) names.push(prefix ? name.slice(1) : name);
      }
      if (Object.getOwnPropertySymbols) {
        return names.concat(Object.getOwnPropertySymbols(events));
      }
      return names;
    };
    EventEmitter.prototype.listeners = function listeners(event) {
      var evt = prefix ? prefix + event : event, handlers = this._events[evt];
      if (!handlers) return [];
      if (handlers.fn) return [handlers.fn];
      for (var i = 0, l = handlers.length, ee = new Array(l); i < l; i++) {
        ee[i] = handlers[i].fn;
      }
      return ee;
    };
    EventEmitter.prototype.listenerCount = function listenerCount(event) {
      var evt = prefix ? prefix + event : event, listeners = this._events[evt];
      if (!listeners) return 0;
      if (listeners.fn) return 1;
      return listeners.length;
    };
    EventEmitter.prototype.emit = function emit(event, a1, a2, a3, a4, a5) {
      var evt = prefix ? prefix + event : event;
      if (!this._events[evt]) return false;
      var listeners = this._events[evt], len = arguments.length, args, i;
      if (listeners.fn) {
        if (listeners.once) this.removeListener(event, listeners.fn, void 0, true);
        switch (len) {
          case 1:
            return listeners.fn.call(listeners.context), true;
          case 2:
            return listeners.fn.call(listeners.context, a1), true;
          case 3:
            return listeners.fn.call(listeners.context, a1, a2), true;
          case 4:
            return listeners.fn.call(listeners.context, a1, a2, a3), true;
          case 5:
            return listeners.fn.call(listeners.context, a1, a2, a3, a4), true;
          case 6:
            return listeners.fn.call(listeners.context, a1, a2, a3, a4, a5), true;
        }
        for (i = 1, args = new Array(len - 1); i < len; i++) {
          args[i - 1] = arguments[i];
        }
        listeners.fn.apply(listeners.context, args);
      } else {
        var length = listeners.length, j;
        for (i = 0; i < length; i++) {
          if (listeners[i].once) this.removeListener(event, listeners[i].fn, void 0, true);
          switch (len) {
            case 1:
              listeners[i].fn.call(listeners[i].context);
              break;
            case 2:
              listeners[i].fn.call(listeners[i].context, a1);
              break;
            case 3:
              listeners[i].fn.call(listeners[i].context, a1, a2);
              break;
            case 4:
              listeners[i].fn.call(listeners[i].context, a1, a2, a3);
              break;
            default:
              if (!args) for (j = 1, args = new Array(len - 1); j < len; j++) {
                args[j - 1] = arguments[j];
              }
              listeners[i].fn.apply(listeners[i].context, args);
          }
        }
      }
      return true;
    };
    EventEmitter.prototype.on = function on(event, fn, context) {
      return addListener(this, event, fn, context, false);
    };
    EventEmitter.prototype.once = function once(event, fn, context) {
      return addListener(this, event, fn, context, true);
    };
    EventEmitter.prototype.removeListener = function removeListener(event, fn, context, once) {
      var evt = prefix ? prefix + event : event;
      if (!this._events[evt]) return this;
      if (!fn) {
        clearEvent(this, evt);
        return this;
      }
      var listeners = this._events[evt];
      if (listeners.fn) {
        if (listeners.fn === fn && (!once || listeners.once) && (!context || listeners.context === context)) {
          clearEvent(this, evt);
        }
      } else {
        for (var i = 0, events = [], length = listeners.length; i < length; i++) {
          if (listeners[i].fn !== fn || once && !listeners[i].once || context && listeners[i].context !== context) {
            events.push(listeners[i]);
          }
        }
        if (events.length) this._events[evt] = events.length === 1 ? events[0] : events;
        else clearEvent(this, evt);
      }
      return this;
    };
    EventEmitter.prototype.removeAllListeners = function removeAllListeners(event) {
      var evt;
      if (event) {
        evt = prefix ? prefix + event : event;
        if (this._events[evt]) clearEvent(this, evt);
      } else {
        this._events = new Events();
        this._eventsCount = 0;
      }
      return this;
    };
    EventEmitter.prototype.off = EventEmitter.prototype.removeListener;
    EventEmitter.prototype.addListener = EventEmitter.prototype.on;
    EventEmitter.prefixed = prefix;
    EventEmitter.EventEmitter = EventEmitter;
    if ("undefined" !== typeof module2) {
      module2.exports = EventEmitter;
    }
  }
});

// node_modules/obsidian-dev-utils/dist/lib/Error.cjs
var require_Error = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/Error.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var Error_exports = {};
    __export2(Error_exports, {
      emitAsyncErrorEvent: () => emitAsyncErrorEvent,
      errorToString: () => errorToString,
      getStackTrace: () => getStackTrace,
      printError: () => printError,
      registerAsyncErrorEventHandler: () => registerAsyncErrorEventHandler,
      throwExpression: () => throwExpression
    });
    module2.exports = __toCommonJS2(Error_exports);
    var import_eventemitter3 = require_eventemitter3();
    var ASYNC_ERROR_EVENT = "asyncError";
    var asyncErrorEventEmitter = new import_eventemitter3.EventEmitter();
    asyncErrorEventEmitter.on(ASYNC_ERROR_EVENT, handleAsyncError);
    function emitAsyncErrorEvent(asyncError) {
      asyncErrorEventEmitter.emit(ASYNC_ERROR_EVENT, asyncError);
    }
    function errorToString(error) {
      return parseErrorEntries(error).map((entry) => "  ".repeat(entry.level) + entry.message).join("\n");
    }
    function getStackTrace() {
      const stack = new Error().stack ?? "";
      const lines = stack.split("\n");
      return lines.slice(2).join("\n");
    }
    function printError(error) {
      const entries = parseErrorEntries(error);
      for (const entry of entries) {
        if (entry.shouldClearAnsiSequence) {
          console.error(`\x1B[0m${entry.message}\x1B[0m`);
        } else {
          console.error(entry.message);
        }
      }
    }
    function registerAsyncErrorEventHandler(handler) {
      asyncErrorEventEmitter.on(ASYNC_ERROR_EVENT, handler);
      return () => asyncErrorEventEmitter.off(ASYNC_ERROR_EVENT, handler);
    }
    function throwExpression(error) {
      throw error;
    }
    function handleAsyncError(asyncError) {
      printError(new Error("An unhandled error occurred executing async operation", { cause: asyncError }));
    }
    function parseErrorEntries(error, level = 0, entries = []) {
      if (error === void 0) {
        return entries;
      }
      if (!(error instanceof Error)) {
        let str = "";
        if (error === null) {
          str = "(null)";
        } else if (typeof error === "string") {
          str = error;
        } else {
          str = JSON.stringify(error);
        }
        entries.push({ level, message: str });
        return entries;
      }
      const title = `${error.name}: ${error.message}`;
      entries.push({ level, message: title, shouldClearAnsiSequence: true });
      if (error.stack) {
        const restStack = error.stack.startsWith(title) ? error.stack.slice(title.length + 1) : error.stack;
        entries.push({ level, message: `Error stack:
${restStack}` });
      }
      if (error.cause !== void 0) {
        entries.push({ level, message: "Caused by:" });
        parseErrorEntries(error.cause, level + 1, entries);
      }
      return entries;
    }
  }
});

// node_modules/obsidian-dev-utils/dist/lib/Async.cjs
var require_Async = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/Async.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var Async_exports = {};
    __export2(Async_exports, {
      addErrorHandler: () => addErrorHandler,
      asyncFilter: () => asyncFilter,
      asyncFlatMap: () => asyncFlatMap,
      asyncMap: () => asyncMap,
      convertAsyncToSync: () => convertAsyncToSync,
      convertSyncToAsync: () => convertSyncToAsync,
      invokeAsyncSafely: () => invokeAsyncSafely2,
      marksAsTerminateRetry: () => marksAsTerminateRetry,
      retryWithTimeout: () => retryWithTimeout,
      runWithTimeout: () => runWithTimeout,
      sleep: () => sleep,
      timeout: () => timeout,
      toArray: () => toArray
    });
    module2.exports = __toCommonJS2(Async_exports);
    var import_Debug = require_Debug();
    var import_Error = require_Error();
    async function addErrorHandler(asyncFn) {
      try {
        await asyncFn();
      } catch (asyncError) {
        (0, import_Error.emitAsyncErrorEvent)(asyncError);
      }
    }
    async function asyncFilter(arr, predicate) {
      const predicateResults = await asyncMap(arr, predicate);
      return arr.filter((_, index) => predicateResults[index]);
    }
    async function asyncFlatMap(arr, callback) {
      return (await asyncMap(arr, callback)).flat();
    }
    async function asyncMap(arr, callback) {
      return await Promise.all(arr.map(callback));
    }
    function convertAsyncToSync(asyncFunc) {
      return (...args) => {
        invokeAsyncSafely2(() => asyncFunc(...args));
      };
    }
    function convertSyncToAsync(syncFn) {
      return (...args) => Promise.resolve().then(() => syncFn(...args));
    }
    function invokeAsyncSafely2(asyncFn) {
      void addErrorHandler(asyncFn);
    }
    function marksAsTerminateRetry(error) {
      return Object.assign(error, { __terminateRetry: true });
    }
    async function retryWithTimeout(fn, retryOptions = {}) {
      const stackTrace = (0, import_Error.getStackTrace)();
      const DEFAULT_RETRY_OPTIONS = {
        retryDelayInMilliseconds: 100,
        shouldRetryOnError: false,
        timeoutInMilliseconds: 5e3
      };
      const fullOptions = { ...DEFAULT_RETRY_OPTIONS, ...retryOptions };
      await runWithTimeout(fullOptions.timeoutInMilliseconds, async () => {
        let attempt = 0;
        for (; ; ) {
          fullOptions.abortSignal?.throwIfAborted();
          attempt++;
          let isSuccess;
          try {
            isSuccess = await fn();
          } catch (error) {
            if (!fullOptions.shouldRetryOnError || error.__terminateRetry) {
              throw error;
            }
            (0, import_Error.printError)(error);
            isSuccess = false;
          }
          if (isSuccess) {
            if (attempt > 1) {
              console.debug(`Retry completed successfully after ${attempt.toString()} attempts`);
            }
            return;
          }
          console.debug(`Retry attempt ${attempt.toString()} completed unsuccessfully. Trying again in ${fullOptions.retryDelayInMilliseconds.toString()} milliseconds`, {
            fn,
            stackTrace
          });
          await sleep(fullOptions.retryDelayInMilliseconds);
        }
      });
    }
    async function runWithTimeout(timeoutInMilliseconds, fn) {
      let isTimedOut = true;
      let result = null;
      const startTime = performance.now();
      await Promise.race([run(), timeout2()]);
      if (isTimedOut) {
        throw new Error("Timed out");
      }
      return result;
      async function run() {
        result = await fn();
        isTimedOut = false;
        const duration = performance.now() - startTime;
        console.debug(`Execution time: ${duration.toString()} milliseconds`, { fn });
      }
      async function timeout2() {
        if (!isTimedOut) {
          return;
        }
        await sleep(timeoutInMilliseconds);
        if (!isTimedOut) {
          return;
        }
        const duration = performance.now() - startTime;
        console.warn(`Timed out in ${duration.toString()} milliseconds`, { fn });
        if ((0, import_Debug.isDebug)()) {
          console.warn("The execution is not terminated because window.DEBUG is set");
          await timeout2();
        }
      }
    }
    async function sleep(milliseconds) {
      await new Promise((resolve) => setTimeout(resolve, milliseconds));
    }
    async function timeout(timeoutInMilliseconds) {
      await sleep(timeoutInMilliseconds);
      throw new Error(`Timed out in ${timeoutInMilliseconds.toString()} milliseconds`);
    }
    async function toArray(iter) {
      const arr = [];
      for await (const item of iter) {
        arr.push(item);
      }
      return arr;
    }
  }
});

// node_modules/obsidian-typings/dist/implementations.cjs
var require_implementations = __commonJS({
  "node_modules/obsidian-typings/dist/implementations.cjs"(exports2, module2) {
    "use strict";
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var implementations_exports = {};
    __export2(implementations_exports, {
      CustomArrayDictImpl: () => CustomArrayDictImpl,
      FileExtension: () => FileExtension,
      InternalPluginName: () => InternalPluginName,
      ViewType: () => ViewType,
      createTFileInstance: () => createTFileInstance,
      createTFolderInstance: () => createTFolderInstance,
      getAllPropertiesViewConstructor: () => getAllPropertiesViewConstructor,
      getAppConstructor: () => getAppConstructor,
      getAudioViewConstructor: () => getAudioViewConstructor,
      getBacklinkViewConstructor: () => getBacklinkViewConstructor,
      getBookmarksViewConstructor: () => getBookmarksViewConstructor,
      getBrowserHistoryViewConstructor: () => getBrowserHistoryViewConstructor,
      getBrowserViewConstructor: () => getBrowserViewConstructor,
      getCanvasViewConstructor: () => getCanvasViewConstructor,
      getEmptyViewConstructor: () => getEmptyViewConstructor,
      getFileExplorerViewConstructor: () => getFileExplorerViewConstructor,
      getFilePropertiesViewConstructor: () => getFilePropertiesViewConstructor,
      getGraphViewConstructor: () => getGraphViewConstructor,
      getImageViewConstructor: () => getImageViewConstructor,
      getInternalPluginConstructor: () => getInternalPluginConstructor,
      getInternalPluginsConstructor: () => getInternalPluginsConstructor,
      getLocalGraphViewConstructor: () => getLocalGraphViewConstructor,
      getMarkdownViewConstructor: () => getMarkdownViewConstructor,
      getOutgoingLinkViewConstructor: () => getOutgoingLinkViewConstructor,
      getOutlineViewConstructor: () => getOutlineViewConstructor,
      getPdfViewConstructor: () => getPdfViewConstructor,
      getReleaseNotesViewConstructor: () => getReleaseNotesViewConstructor,
      getSearchViewConstructor: () => getSearchViewConstructor,
      getSyncViewConstructor: () => getSyncViewConstructor,
      getTFileConstructor: () => getTFileConstructor,
      getTFolderConstructor: () => getTFolderConstructor,
      getTagViewConstructor: () => getTagViewConstructor,
      getVideoViewConstructor: () => getVideoViewConstructor,
      getViewConstructorByViewType: () => getViewConstructorByViewType,
      isEmbedCache: () => isEmbedCache,
      isFrontmatterLinkCache: () => isFrontmatterLinkCache,
      isLinkCache: () => isLinkCache,
      isReferenceCache: () => isReferenceCache,
      parentFolderPath: () => parentFolderPath
    });
    module2.exports = __toCommonJS2(implementations_exports);
    var import_obsidian3 = require("obsidian");
    function getTFolderConstructor() {
      return import_obsidian3.TFolder;
    }
    function parentFolderPath(path) {
      return path.replace(/\/?[^\/]*$/, "") || "/";
    }
    function createTFolderInstance(app, path) {
      let folder = app.vault.getFolderByPath(path);
      if (folder) {
        return folder;
      }
      folder = new (getTFolderConstructor())(app.vault, path);
      folder.parent = createTFolderInstance(app, parentFolderPath(path));
      folder.deleted = true;
      return folder;
    }
    var import_obsidian22 = require("obsidian");
    function getTFileConstructor() {
      return import_obsidian22.TFile;
    }
    function createTFileInstance(app, path) {
      let file = app.vault.getFileByPath(path);
      if (file) {
        return file;
      }
      file = new (getTFileConstructor())(app.vault, path);
      file.parent = createTFolderInstance(app, parentFolderPath(path));
      file.deleted = true;
      return file;
    }
    var CustomArrayDictImpl = class {
      data = /* @__PURE__ */ new Map();
      add(key, value) {
        let values = this.get(key);
        if (!values) {
          values = [];
          this.data.set(key, values);
        }
        if (!values.includes(value)) {
          values.push(value);
        }
      }
      remove(key, value) {
        const values = this.get(key);
        if (!values) {
          return;
        }
        values.remove(value);
        if (values.length === 0) {
          this.clear(key);
        }
      }
      get(key) {
        return this.data.get(key) || null;
      }
      keys() {
        return Array.from(this.data.keys());
      }
      clear(key) {
        this.data.delete(key);
      }
      clearAll() {
        this.data.clear();
      }
      contains(key, value) {
        return !!this.get(key)?.contains(value);
      }
      count() {
        let ans = 0;
        for (const key in this.keys()) {
          ans += this.get(key)?.length ?? 0;
        }
        return ans;
      }
    };
    var FileExtension = {
      _3gp: "3gp",
      avif: "avif",
      bmp: "bmp",
      canvas: "canvas",
      flac: "flac",
      gif: "gif",
      jpeg: "jpeg",
      jpg: "jpg",
      m4a: "m4a",
      md: "md",
      mkv: "mkv",
      mov: "mov",
      mp3: "mp3",
      mp4: "mp4",
      oga: "oga",
      ogg: "ogg",
      ogv: "ogv",
      opus: "opus",
      pdf: "pdf",
      png: "png",
      svg: "svg",
      wav: "wav",
      webm: "webm",
      webp: "webp"
    };
    var InternalPluginName = {
      /**
       * Plugin name in UI: Audio recorder
       */
      AudioRecorder: "audio-recorder",
      /**
       * Plugin name in UI: Backlinks
       */
      Backlink: "backlink",
      /**
       * Plugin name in UI: Bookmarks
       */
      Bookmarks: "bookmarks",
      /**
       * Plugin name in UI: Web viewer
       */
      Browser: "browser",
      /**
       * Plugin name in UI: Canvas
       */
      Canvas: "canvas",
      /**
       * Plugin name in UI: Command palette
       */
      CommandPalette: "command-palette",
      /**
       * Plugin name in UI: Daily notes
       */
      DailyNotes: "daily-notes",
      /**
       * Plugin name in UI: (hidden)
       */
      EditorStatus: "editor-status",
      /**
       * Plugin name in UI: Files
       */
      FileExplorer: "file-explorer",
      /**
       * Plugin name in UI: File recovery
       */
      FileRecovery: "file-recovery",
      /**
       * Plugin name in UI: Search
       */
      GlobalSearch: "global-search",
      /**
       * Plugin name in UI: Graph view
       */
      Graph: "graph",
      /**
       * Plugin name in UI: Format converter
       */
      MarkdownImporter: "markdown-importer",
      /**
       * Plugin name in UI: Note composer
       */
      NoteComposer: "note-composer",
      /**
       * Plugin name in UI: Outgoing links
       */
      OutgoingLink: "outgoing-link",
      /**
       * Plugin name in UI: Outline
       */
      Outline: "outline",
      /**
       * Plugin name in UI: Page preview
       */
      PagePreview: "page-preview",
      /**
       * Plugin name in UI: Properties view
       */
      Properties: "properties",
      /**
       * Plugin name in UI: Publish
       */
      Publish: "publish",
      /**
       * Plugin name in UI: Random note
       */
      RandomNote: "random-note",
      /**
       * Plugin name in UI: Slash commands
       */
      SlashCommand: "slash-command",
      /**
       * Plugin name in UI: Slides
       */
      Slides: "slides",
      /**
       * Plugin name in UI: Quick Switcher
       */
      Switcher: "switcher",
      /**
       * Plugin name in UI: Sync
       */
      Sync: "sync",
      /**
       * Plugin name in UI: Tags view
       */
      TagPane: "tag-pane",
      /**
       * Plugin name in UI: Templates
       */
      Templates: "templates",
      /**
       * Plugin name in UI: Word count
       */
      WordCount: "word-count",
      /**
       * Plugin name in UI: Workspaces
       */
      Workspaces: "workspaces",
      /**
       * Plugin name in UI: Unique note creator
       */
      ZkPrefixer: "zk-prefixer"
    };
    var ViewType = {
      AllProperties: "all-properties",
      Audio: "audio",
      Backlink: InternalPluginName.Backlink,
      Bookmarks: InternalPluginName.Bookmarks,
      Browser: "browser",
      BrowserHistory: "browser-history",
      Canvas: InternalPluginName.Canvas,
      Empty: "empty",
      FileExplorer: InternalPluginName.FileExplorer,
      FileProperties: "file-properties",
      Graph: InternalPluginName.Graph,
      Image: "image",
      LocalGraph: "localgraph",
      Markdown: "markdown",
      OutgoingLink: InternalPluginName.OutgoingLink,
      Outline: InternalPluginName.Outline,
      Pdf: "pdf",
      ReleaseNotes: "release-notes",
      Search: "search",
      Sync: "sync",
      Tag: "tag",
      Video: "video"
    };
    function getInternalPluginConstructor(app) {
      const anyPlugin = Object.values(app.internalPlugins.plugins)[0];
      if (!anyPlugin) {
        throw new Error("No internal plugin found");
      }
      return anyPlugin.constructor;
    }
    function getInternalPluginsConstructor(app) {
      return app.internalPlugins.constructor;
    }
    var import_obsidian32 = require("obsidian");
    function getAppConstructor() {
      return import_obsidian32.App;
    }
    function isReferenceCache(reference) {
      return !!reference.position;
    }
    function isEmbedCache(reference) {
      return isReferenceCache(reference) && reference.original[0] === "!";
    }
    function isFrontmatterLinkCache(reference) {
      return !!reference.key;
    }
    function isLinkCache(reference) {
      return isReferenceCache(reference) && reference.original[0] !== "!";
    }
    function getViewConstructorByViewType(app, viewType) {
      const leaf = app.workspace.createLeafInTabGroup();
      try {
        const viewCreator = app.viewRegistry.getViewCreatorByType(viewType);
        if (!viewCreator) {
          throw new Error("View creator not found");
        }
        const view = viewCreator(leaf);
        return view.constructor;
      } finally {
        leaf.detach();
      }
    }
    function getOutlineViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Outline);
    }
    function getBrowserViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Browser);
    }
    function getReleaseNotesViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.ReleaseNotes);
    }
    function getPdfViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Pdf);
    }
    function getSyncViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Sync);
    }
    function getOutgoingLinkViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.OutgoingLink);
    }
    function getCanvasViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Canvas);
    }
    function getTagViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Tag);
    }
    function getAudioViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Audio);
    }
    function getLocalGraphViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.LocalGraph);
    }
    function getBacklinkViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Backlink);
    }
    function getFileExplorerViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.FileExplorer);
    }
    function getSearchViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Search);
    }
    function getVideoViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Video);
    }
    function getImageViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Image);
    }
    function getBrowserHistoryViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.BrowserHistory);
    }
    function getEmptyViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Empty);
    }
    function getGraphViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Graph);
    }
    function getFilePropertiesViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.FileProperties);
    }
    function getBookmarksViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Bookmarks);
    }
    function getMarkdownViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.Markdown);
    }
    function getAllPropertiesViewConstructor(app) {
      return getViewConstructorByViewType(app, ViewType.AllProperties);
    }
  }
});

// node_modules/path-browserify/index.js
var require_path_browserify = __commonJS({
  "node_modules/path-browserify/index.js"(exports2, module2) {
    var __process = globalThis["process"] ?? {
      "cwd": () => "/",
      "env": {},
      "platform": "android"
    };
    function assertPath(path) {
      if (typeof path !== "string") {
        throw new TypeError("Path must be a string. Received " + JSON.stringify(path));
      }
    }
    function normalizeStringPosix(path, allowAboveRoot) {
      var res = "";
      var lastSegmentLength = 0;
      var lastSlash = -1;
      var dots = 0;
      var code;
      for (var i = 0; i <= path.length; ++i) {
        if (i < path.length)
          code = path.charCodeAt(i);
        else if (code === 47)
          break;
        else
          code = 47;
        if (code === 47) {
          if (lastSlash === i - 1 || dots === 1) {
          } else if (lastSlash !== i - 1 && dots === 2) {
            if (res.length < 2 || lastSegmentLength !== 2 || res.charCodeAt(res.length - 1) !== 46 || res.charCodeAt(res.length - 2) !== 46) {
              if (res.length > 2) {
                var lastSlashIndex = res.lastIndexOf("/");
                if (lastSlashIndex !== res.length - 1) {
                  if (lastSlashIndex === -1) {
                    res = "";
                    lastSegmentLength = 0;
                  } else {
                    res = res.slice(0, lastSlashIndex);
                    lastSegmentLength = res.length - 1 - res.lastIndexOf("/");
                  }
                  lastSlash = i;
                  dots = 0;
                  continue;
                }
              } else if (res.length === 2 || res.length === 1) {
                res = "";
                lastSegmentLength = 0;
                lastSlash = i;
                dots = 0;
                continue;
              }
            }
            if (allowAboveRoot) {
              if (res.length > 0)
                res += "/..";
              else
                res = "..";
              lastSegmentLength = 2;
            }
          } else {
            if (res.length > 0)
              res += "/" + path.slice(lastSlash + 1, i);
            else
              res = path.slice(lastSlash + 1, i);
            lastSegmentLength = i - lastSlash - 1;
          }
          lastSlash = i;
          dots = 0;
        } else if (code === 46 && dots !== -1) {
          ++dots;
        } else {
          dots = -1;
        }
      }
      return res;
    }
    function _format(sep, pathObject) {
      var dir = pathObject.dir || pathObject.root;
      var base = pathObject.base || (pathObject.name || "") + (pathObject.ext || "");
      if (!dir) {
        return base;
      }
      if (dir === pathObject.root) {
        return dir + base;
      }
      return dir + sep + base;
    }
    var posix = {
      // path.resolve([from ...], to)
      resolve: function resolve() {
        var resolvedPath = "";
        var resolvedAbsolute = false;
        var cwd;
        for (var i = arguments.length - 1; i >= -1 && !resolvedAbsolute; i--) {
          var path;
          if (i >= 0)
            path = arguments[i];
          else {
            if (cwd === void 0)
              cwd = __process.cwd();
            path = cwd;
          }
          assertPath(path);
          if (path.length === 0) {
            continue;
          }
          resolvedPath = path + "/" + resolvedPath;
          resolvedAbsolute = path.charCodeAt(0) === 47;
        }
        resolvedPath = normalizeStringPosix(resolvedPath, !resolvedAbsolute);
        if (resolvedAbsolute) {
          if (resolvedPath.length > 0)
            return "/" + resolvedPath;
          else
            return "/";
        } else if (resolvedPath.length > 0) {
          return resolvedPath;
        } else {
          return ".";
        }
      },
      normalize: function normalize(path) {
        assertPath(path);
        if (path.length === 0) return ".";
        var isAbsolute = path.charCodeAt(0) === 47;
        var trailingSeparator = path.charCodeAt(path.length - 1) === 47;
        path = normalizeStringPosix(path, !isAbsolute);
        if (path.length === 0 && !isAbsolute) path = ".";
        if (path.length > 0 && trailingSeparator) path += "/";
        if (isAbsolute) return "/" + path;
        return path;
      },
      isAbsolute: function isAbsolute(path) {
        assertPath(path);
        return path.length > 0 && path.charCodeAt(0) === 47;
      },
      join: function join() {
        if (arguments.length === 0)
          return ".";
        var joined;
        for (var i = 0; i < arguments.length; ++i) {
          var arg = arguments[i];
          assertPath(arg);
          if (arg.length > 0) {
            if (joined === void 0)
              joined = arg;
            else
              joined += "/" + arg;
          }
        }
        if (joined === void 0)
          return ".";
        return posix.normalize(joined);
      },
      relative: function relative(from, to) {
        assertPath(from);
        assertPath(to);
        if (from === to) return "";
        from = posix.resolve(from);
        to = posix.resolve(to);
        if (from === to) return "";
        var fromStart = 1;
        for (; fromStart < from.length; ++fromStart) {
          if (from.charCodeAt(fromStart) !== 47)
            break;
        }
        var fromEnd = from.length;
        var fromLen = fromEnd - fromStart;
        var toStart = 1;
        for (; toStart < to.length; ++toStart) {
          if (to.charCodeAt(toStart) !== 47)
            break;
        }
        var toEnd = to.length;
        var toLen = toEnd - toStart;
        var length = fromLen < toLen ? fromLen : toLen;
        var lastCommonSep = -1;
        var i = 0;
        for (; i <= length; ++i) {
          if (i === length) {
            if (toLen > length) {
              if (to.charCodeAt(toStart + i) === 47) {
                return to.slice(toStart + i + 1);
              } else if (i === 0) {
                return to.slice(toStart + i);
              }
            } else if (fromLen > length) {
              if (from.charCodeAt(fromStart + i) === 47) {
                lastCommonSep = i;
              } else if (i === 0) {
                lastCommonSep = 0;
              }
            }
            break;
          }
          var fromCode = from.charCodeAt(fromStart + i);
          var toCode = to.charCodeAt(toStart + i);
          if (fromCode !== toCode)
            break;
          else if (fromCode === 47)
            lastCommonSep = i;
        }
        var out = "";
        for (i = fromStart + lastCommonSep + 1; i <= fromEnd; ++i) {
          if (i === fromEnd || from.charCodeAt(i) === 47) {
            if (out.length === 0)
              out += "..";
            else
              out += "/..";
          }
        }
        if (out.length > 0)
          return out + to.slice(toStart + lastCommonSep);
        else {
          toStart += lastCommonSep;
          if (to.charCodeAt(toStart) === 47)
            ++toStart;
          return to.slice(toStart);
        }
      },
      _makeLong: function _makeLong(path) {
        return path;
      },
      dirname: function dirname(path) {
        assertPath(path);
        if (path.length === 0) return ".";
        var code = path.charCodeAt(0);
        var hasRoot = code === 47;
        var end = -1;
        var matchedSlash = true;
        for (var i = path.length - 1; i >= 1; --i) {
          code = path.charCodeAt(i);
          if (code === 47) {
            if (!matchedSlash) {
              end = i;
              break;
            }
          } else {
            matchedSlash = false;
          }
        }
        if (end === -1) return hasRoot ? "/" : ".";
        if (hasRoot && end === 1) return "//";
        return path.slice(0, end);
      },
      basename: function basename(path, ext) {
        if (ext !== void 0 && typeof ext !== "string") throw new TypeError('"ext" argument must be a string');
        assertPath(path);
        var start = 0;
        var end = -1;
        var matchedSlash = true;
        var i;
        if (ext !== void 0 && ext.length > 0 && ext.length <= path.length) {
          if (ext.length === path.length && ext === path) return "";
          var extIdx = ext.length - 1;
          var firstNonSlashEnd = -1;
          for (i = path.length - 1; i >= 0; --i) {
            var code = path.charCodeAt(i);
            if (code === 47) {
              if (!matchedSlash) {
                start = i + 1;
                break;
              }
            } else {
              if (firstNonSlashEnd === -1) {
                matchedSlash = false;
                firstNonSlashEnd = i + 1;
              }
              if (extIdx >= 0) {
                if (code === ext.charCodeAt(extIdx)) {
                  if (--extIdx === -1) {
                    end = i;
                  }
                } else {
                  extIdx = -1;
                  end = firstNonSlashEnd;
                }
              }
            }
          }
          if (start === end) end = firstNonSlashEnd;
          else if (end === -1) end = path.length;
          return path.slice(start, end);
        } else {
          for (i = path.length - 1; i >= 0; --i) {
            if (path.charCodeAt(i) === 47) {
              if (!matchedSlash) {
                start = i + 1;
                break;
              }
            } else if (end === -1) {
              matchedSlash = false;
              end = i + 1;
            }
          }
          if (end === -1) return "";
          return path.slice(start, end);
        }
      },
      extname: function extname(path) {
        assertPath(path);
        var startDot = -1;
        var startPart = 0;
        var end = -1;
        var matchedSlash = true;
        var preDotState = 0;
        for (var i = path.length - 1; i >= 0; --i) {
          var code = path.charCodeAt(i);
          if (code === 47) {
            if (!matchedSlash) {
              startPart = i + 1;
              break;
            }
            continue;
          }
          if (end === -1) {
            matchedSlash = false;
            end = i + 1;
          }
          if (code === 46) {
            if (startDot === -1)
              startDot = i;
            else if (preDotState !== 1)
              preDotState = 1;
          } else if (startDot !== -1) {
            preDotState = -1;
          }
        }
        if (startDot === -1 || end === -1 || // We saw a non-dot character immediately before the dot
        preDotState === 0 || // The (right-most) trimmed path component is exactly '..'
        preDotState === 1 && startDot === end - 1 && startDot === startPart + 1) {
          return "";
        }
        return path.slice(startDot, end);
      },
      format: function format(pathObject) {
        if (pathObject === null || typeof pathObject !== "object") {
          throw new TypeError('The "pathObject" argument must be of type Object. Received type ' + typeof pathObject);
        }
        return _format("/", pathObject);
      },
      parse: function parse(path) {
        assertPath(path);
        var ret = { root: "", dir: "", base: "", ext: "", name: "" };
        if (path.length === 0) return ret;
        var code = path.charCodeAt(0);
        var isAbsolute = code === 47;
        var start;
        if (isAbsolute) {
          ret.root = "/";
          start = 1;
        } else {
          start = 0;
        }
        var startDot = -1;
        var startPart = 0;
        var end = -1;
        var matchedSlash = true;
        var i = path.length - 1;
        var preDotState = 0;
        for (; i >= start; --i) {
          code = path.charCodeAt(i);
          if (code === 47) {
            if (!matchedSlash) {
              startPart = i + 1;
              break;
            }
            continue;
          }
          if (end === -1) {
            matchedSlash = false;
            end = i + 1;
          }
          if (code === 46) {
            if (startDot === -1) startDot = i;
            else if (preDotState !== 1) preDotState = 1;
          } else if (startDot !== -1) {
            preDotState = -1;
          }
        }
        if (startDot === -1 || end === -1 || // We saw a non-dot character immediately before the dot
        preDotState === 0 || // The (right-most) trimmed path component is exactly '..'
        preDotState === 1 && startDot === end - 1 && startDot === startPart + 1) {
          if (end !== -1) {
            if (startPart === 0 && isAbsolute) ret.base = ret.name = path.slice(1, end);
            else ret.base = ret.name = path.slice(startPart, end);
          }
        } else {
          if (startPart === 0 && isAbsolute) {
            ret.name = path.slice(1, startDot);
            ret.base = path.slice(1, end);
          } else {
            ret.name = path.slice(startPart, startDot);
            ret.base = path.slice(startPart, end);
          }
          ret.ext = path.slice(startDot, end);
        }
        if (startPart > 0) ret.dir = path.slice(0, startPart - 1);
        else if (isAbsolute) ret.dir = "/";
        return ret;
      },
      sep: "/",
      delimiter: ":",
      win32: null,
      posix: null
    };
    posix.posix = posix;
    module2.exports = posix;
  }
});

// node_modules/obsidian-dev-utils/dist/lib/RegExp.cjs
var require_RegExp = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/RegExp.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var RegExp_exports = {};
    __export2(RegExp_exports, {
      escapeRegExp: () => escapeRegExp,
      isValidRegExp: () => isValidRegExp
    });
    module2.exports = __toCommonJS2(RegExp_exports);
    function escapeRegExp(str) {
      return str.replaceAll(/[.*+?^${}()|[\]\\]/g, "\\$&");
    }
    function isValidRegExp(str) {
      try {
        new RegExp(str);
        return true;
      } catch {
        return false;
      }
    }
  }
});

// node_modules/obsidian-dev-utils/dist/lib/ValueProvider.cjs
var require_ValueProvider = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/ValueProvider.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var ValueProvider_exports = {};
    __export2(ValueProvider_exports, {
      resolveValue: () => resolveValue
    });
    module2.exports = __toCommonJS2(ValueProvider_exports);
    async function resolveValue(provider, ...args) {
      if (isFunction(provider)) {
        return await provider(...args);
      } else {
        return provider;
      }
    }
    function isFunction(value) {
      return typeof value === "function";
    }
  }
});

// node_modules/obsidian-dev-utils/dist/lib/String.cjs
var require_String = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/String.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var String_exports = {};
    __export2(String_exports, {
      ensureEndsWith: () => ensureEndsWith,
      ensureStartsWith: () => ensureStartsWith,
      escape: () => escape,
      insertAt: () => insertAt,
      makeValidVariableName: () => makeValidVariableName,
      normalize: () => normalize,
      replace: () => replace,
      replaceAllAsync: () => replaceAllAsync,
      trimEnd: () => trimEnd,
      trimStart: () => trimStart,
      unescape: () => unescape
    });
    module2.exports = __toCommonJS2(String_exports);
    var import_Error = require_Error();
    var import_RegExp = require_RegExp();
    var import_ValueProvider = require_ValueProvider();
    var ESCAPE_MAP = {
      "\n": "\\n",
      "\r": "\\r",
      "	": "\\t",
      "\b": "\\b",
      "\f": "\\f",
      "'": "\\'",
      '"': '\\"',
      "\\": "\\\\"
    };
    var UNESCAPE_MAP = {};
    for (const [key, value] of Object.entries(ESCAPE_MAP)) {
      UNESCAPE_MAP[value] = key;
    }
    function ensureEndsWith(str, suffix) {
      return str.endsWith(suffix) ? str : str + suffix;
    }
    function ensureStartsWith(str, prefix) {
      return str.startsWith(prefix) ? str : prefix + str;
    }
    function escape(str) {
      return replace(str, ESCAPE_MAP);
    }
    function insertAt(str, substring, startIndex, endIndex) {
      endIndex ??= startIndex;
      return str.slice(0, startIndex) + substring + str.slice(endIndex);
    }
    function makeValidVariableName(str) {
      return str.replace(/[^a-zA-Z0-9_]/g, "_");
    }
    function normalize(str) {
      return str.replace(/\u00A0|\u202F/g, " ").normalize("NFC");
    }
    function replace(str, replacementsMap) {
      const regExp = new RegExp(Object.keys(replacementsMap).map((source) => (0, import_RegExp.escapeRegExp)(source)).join("|"), "g");
      return str.replaceAll(regExp, (source) => replacementsMap[source] ?? (0, import_Error.throwExpression)(new Error(`Unexpected replacement source: ${source}`)));
    }
    async function replaceAllAsync(str, searchValue, replacer) {
      const replacementPromises = [];
      str.replaceAll(searchValue, (substring, ...args) => {
        replacementPromises.push((0, import_ValueProvider.resolveValue)(replacer, substring, ...args));
        return substring;
      });
      const replacements = await Promise.all(replacementPromises);
      return str.replaceAll(searchValue, () => replacements.shift() ?? (0, import_Error.throwExpression)(new Error("Unexpected empty replacement")));
    }
    function trimEnd(str, suffix, shouldValidate) {
      if (str.endsWith(suffix)) {
        return str.slice(0, -suffix.length);
      }
      if (shouldValidate) {
        throw new Error(`String ${str} does not end with suffix ${suffix}`);
      }
      return str;
    }
    function trimStart(str, prefix, validate) {
      if (str.startsWith(prefix)) {
        return str.slice(prefix.length);
      }
      if (validate) {
        throw new Error(`String ${str} does not start with prefix ${prefix}`);
      }
      return str;
    }
    function unescape(str) {
      return replace(str, UNESCAPE_MAP);
    }
  }
});

// node_modules/obsidian-dev-utils/dist/lib/Path.cjs
var require_Path = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/Path.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __create2 = Object.create;
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __getProtoOf2 = Object.getPrototypeOf;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toESM2 = (mod, isNodeMode, target) => (target = mod != null ? __create2(__getProtoOf2(mod)) : {}, __copyProps2(
      // If the importer is in node compatibility mode or this is not an ESM
      // file that has been converted to a CommonJS file using a Babel-
      // compatible transform (i.e. "__esModule" has not been set), then set
      // "default" to the CommonJS "module.exports" for node compatibility.
      isNodeMode || !mod || !mod.__esModule ? __defProp2(target, "default", { value: mod, enumerable: true }) : target,
      mod
    ));
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var Path_exports = {};
    __export2(Path_exports, {
      basename: () => basename,
      delimiter: () => delimiter,
      dirname: () => dirname,
      extname: () => extname,
      format: () => format,
      getDirname: () => getDirname,
      getFilename: () => getFilename,
      isAbsolute: () => isAbsolute,
      join: () => join,
      makeFileName: () => makeFileName,
      normalize: () => normalize,
      normalizeIfRelative: () => normalizeIfRelative,
      parse: () => parse,
      posix: () => posix,
      relative: () => relative,
      resolve: () => resolve,
      sep: () => sep,
      toPosixBuffer: () => toPosixBuffer,
      toPosixPath: () => toPosixPath
    });
    module2.exports = __toCommonJS2(Path_exports);
    var import_path_browserify = __toESM2(__extractDefault(require_path_browserify()), 1);
    var import_String = require_String();
    var WINDOWS_POSIX_LIKE_PATH_REG_EXP = /[a-zA-Z]:\/[^:]*$/;
    var posix = import_path_browserify.default.posix;
    var delimiter = posix.delimiter;
    var sep = import_path_browserify.default.posix.sep;
    var basename = posix.basename;
    var dirname = posix.dirname;
    var extname = posix.extname;
    var format = posix.format;
    function isAbsolute(path2) {
      return posix.isAbsolute(path2) || WINDOWS_POSIX_LIKE_PATH_REG_EXP.exec(path2)?.[0] === path2;
    }
    var join = posix.join;
    var normalize = posix.normalize;
    var parse = posix.parse;
    var relative = posix.relative;
    function getDirname(importMetaUrl) {
      return dirname(getFilename(importMetaUrl));
    }
    function getFilename(importMetaUrl) {
      return resolve(new URL(importMetaUrl).pathname);
    }
    function makeFileName(fileName, extension) {
      return extension ? `${fileName}.${extension}` : fileName;
    }
    function normalizeIfRelative(path2) {
      if (path2.startsWith("/") || path2.includes(":")) {
        return path2;
      }
      return (0, import_String.ensureStartsWith)(path2, "./");
    }
    function resolve(...pathSegments) {
      let path2 = posix.resolve(...pathSegments);
      path2 = toPosixPath(path2);
      const match = WINDOWS_POSIX_LIKE_PATH_REG_EXP.exec(path2);
      return match?.[0] ?? path2;
    }
    function toPosixBuffer(buffer) {
      return Buffer.from(toPosixPath(buffer.toString()));
    }
    function toPosixPath(path2) {
      return path2.replace(/\\/g, "/");
    }
  }
});

// node_modules/obsidian-dev-utils/dist/lib/obsidian/FileSystem.cjs
var require_FileSystem = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/obsidian/FileSystem.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var FileSystem_exports = {};
    __export2(FileSystem_exports, {
      CANVAS_FILE_EXTENSION: () => CANVAS_FILE_EXTENSION,
      MARKDOWN_FILE_EXTENSION: () => MARKDOWN_FILE_EXTENSION,
      checkExtension: () => checkExtension,
      getAbstractFile: () => getAbstractFile,
      getAbstractFileOrNull: () => getAbstractFileOrNull,
      getFile: () => getFile,
      getFileOrNull: () => getFileOrNull,
      getFolder: () => getFolder,
      getFolderOrNull: () => getFolderOrNull,
      getMarkdownFiles: () => getMarkdownFiles,
      getOrCreateFile: () => getOrCreateFile,
      getOrCreateFolder: () => getOrCreateFolder,
      getPath: () => getPath,
      isAbstractFile: () => isAbstractFile,
      isCanvasFile: () => isCanvasFile,
      isFile: () => isFile2,
      isFolder: () => isFolder,
      isMarkdownFile: () => isMarkdownFile2,
      isNote: () => isNote,
      trimMarkdownExtension: () => trimMarkdownExtension
    });
    module2.exports = __toCommonJS2(FileSystem_exports);
    var import_obsidian3 = require("obsidian");
    var import_implementations = require_implementations();
    var import_Path = require_Path();
    var import_String = require_String();
    var MARKDOWN_FILE_EXTENSION = "md";
    var CANVAS_FILE_EXTENSION = "canvas";
    function checkExtension(app, pathOrFile, extension) {
      if (isFile2(pathOrFile)) {
        return pathOrFile.extension === extension;
      }
      if (typeof pathOrFile === "string") {
        const file = getFileOrNull(app, pathOrFile);
        if (file) {
          return file.extension === extension;
        }
        return (0, import_Path.extname)(pathOrFile).slice(1) === extension;
      }
      return false;
    }
    function getAbstractFile(app, pathOrFile, isCaseInsensitive) {
      const file = getAbstractFileOrNull(app, pathOrFile, isCaseInsensitive);
      if (!file) {
        throw new Error(`Abstract file not found: ${pathOrFile}`);
      }
      return file;
    }
    function getAbstractFileOrNull(app, pathOrFile, isCaseInsensitive) {
      if (pathOrFile === null) {
        return null;
      }
      if (isAbstractFile(pathOrFile)) {
        return pathOrFile;
      }
      const file = getFileInternal(app, pathOrFile, isCaseInsensitive);
      if (file) {
        return file;
      }
      const resolvedPath = getResolvedPath(pathOrFile);
      if (resolvedPath === pathOrFile) {
        return null;
      }
      return getFileInternal(app, resolvedPath, isCaseInsensitive);
    }
    function getFile(app, pathOrFile, shouldIncludeNonExisting, isCaseInsensitive) {
      let file = getFileOrNull(app, pathOrFile, isCaseInsensitive);
      if (!file) {
        if (shouldIncludeNonExisting) {
          file = (0, import_implementations.createTFileInstance)(app, pathOrFile);
        } else {
          throw new Error(`File not found: ${pathOrFile}`);
        }
      }
      return file;
    }
    function getFileOrNull(app, pathOrFile, isCaseInsensitive) {
      const file = getAbstractFileOrNull(app, pathOrFile, isCaseInsensitive);
      if (isFile2(file)) {
        return file;
      }
      return null;
    }
    function getFolder(app, pathOrFolder, shouldIncludeNonExisting, isCaseInsensitive) {
      let folder = getFolderOrNull(app, pathOrFolder, isCaseInsensitive);
      if (!folder) {
        if (shouldIncludeNonExisting) {
          folder = (0, import_implementations.createTFolderInstance)(app, pathOrFolder);
        } else {
          throw new Error(`Folder not found: ${pathOrFolder}`);
        }
      }
      return folder;
    }
    function getFolderOrNull(app, pathOrFolder, isCaseInsensitive) {
      const folder = getAbstractFileOrNull(app, pathOrFolder, isCaseInsensitive);
      if (isFolder(folder)) {
        return folder;
      }
      return null;
    }
    function getMarkdownFiles(app, pathOrFolder, isRecursive) {
      const folder = getFolder(app, pathOrFolder);
      let markdownFiles = [];
      if (!isRecursive) {
        markdownFiles = folder.children.filter((file) => isMarkdownFile2(app, file));
      } else {
        import_obsidian3.Vault.recurseChildren(folder, (abstractFile) => {
          if (isMarkdownFile2(app, abstractFile)) {
            markdownFiles.push(abstractFile);
          }
        });
      }
      markdownFiles = markdownFiles.sort((a, b) => a.path.localeCompare(b.path));
      return markdownFiles;
    }
    async function getOrCreateFile(app, path) {
      const file = getFileOrNull(app, path);
      if (file) {
        return file;
      }
      const folderPath = (0, import_implementations.parentFolderPath)(path);
      await getOrCreateFolder(app, folderPath);
      return await app.vault.create(path, "");
    }
    async function getOrCreateFolder(app, path) {
      const folder = getFolderOrNull(app, path);
      if (folder) {
        return folder;
      }
      return await app.vault.createFolder(path);
    }
    function getPath(app, pathOrFile) {
      if (isAbstractFile(pathOrFile)) {
        return pathOrFile.path;
      }
      const file = getAbstractFileOrNull(app, pathOrFile);
      if (file) {
        return file.path;
      }
      return getResolvedPath(pathOrFile);
    }
    function isAbstractFile(file) {
      return file instanceof import_obsidian3.TAbstractFile;
    }
    function isCanvasFile(app, pathOrFile) {
      return checkExtension(app, pathOrFile, CANVAS_FILE_EXTENSION);
    }
    function isFile2(file) {
      return file instanceof import_obsidian3.TFile;
    }
    function isFolder(file) {
      return file instanceof import_obsidian3.TFolder;
    }
    function isMarkdownFile2(app, pathOrFile) {
      return checkExtension(app, pathOrFile, MARKDOWN_FILE_EXTENSION);
    }
    function isNote(app, pathOrFile) {
      return isMarkdownFile2(app, pathOrFile) || isCanvasFile(app, pathOrFile);
    }
    function trimMarkdownExtension(app, file) {
      if (!isMarkdownFile2(app, file)) {
        return file.path;
      }
      return (0, import_String.trimEnd)(file.path, "." + MARKDOWN_FILE_EXTENSION);
    }
    function getFileInternal(app, path, isCaseInsensitive) {
      if (isCaseInsensitive) {
        return app.vault.getAbstractFileByPathInsensitive(path);
      }
      return app.vault.getAbstractFileByPath(path);
    }
    function getResolvedPath(path) {
      return (0, import_obsidian3.normalizePath)((0, import_Path.resolve)("/", path));
    }
  }
});

// node_modules/obsidian-dev-utils/dist/lib/Function.cjs
var require_Function = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/Function.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var Function_exports = {};
    __export2(Function_exports, {
      noop: () => noop,
      noopAsync: () => noopAsync,
      omitAsyncReturnType: () => omitAsyncReturnType,
      omitReturnType: () => omitReturnType
    });
    module2.exports = __toCommonJS2(Function_exports);
    function noop() {
    }
    async function noopAsync() {
    }
    function omitAsyncReturnType(fn) {
      return async (...args) => {
        await fn(...args);
      };
    }
    function omitReturnType(fn) {
      return (...args) => {
        fn(...args);
      };
    }
  }
});

// node_modules/obsidian-dev-utils/dist/lib/obsidian/Plugin/PluginBase.cjs
var require_PluginBase = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/obsidian/Plugin/PluginBase.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var PluginBase_exports = {};
    __export2(PluginBase_exports, {
      PluginBase: () => PluginBase2
    });
    module2.exports = __toCommonJS2(PluginBase_exports);
    var import_obsidian3 = require("obsidian");
    var import_Error = require_Error();
    var import_Function = require_Function();
    var __process = globalThis["process"] ?? {
      "cwd": () => "/",
      "env": {},
      "platform": "android"
    };
    var PluginBase2 = class extends import_obsidian3.Plugin {
      /**
       * Gets the AbortSignal used for aborting long-running operations.
       *
       * @returns The abort signal.
       */
      get abortSignal() {
        return this._abortSignal;
      }
      /**
       * Gets a copy of the current plugin settings.
       *
       * @returns A copy of the plugin settings.
       */
      get settingsCopy() {
        return this.createPluginSettings(this.settings.toJSON());
      }
      /**
       * Gets the plugin settings.
       *
       * @returns The plugin settings.
       */
      get settings() {
        return this._settings;
      }
      _abortSignal;
      _settings;
      notice;
      /**
       * Called when the plugin is loaded
       */
      async onload() {
        this.register((0, import_Error.registerAsyncErrorEventHandler)(() => {
          this.showNotice("An unhandled error occurred. Please check the console for more information.");
        }));
        await this.loadSettings();
        const pluginSettingsTab = this.createPluginSettingsTab();
        if (pluginSettingsTab) {
          this.addSettingTab(pluginSettingsTab);
        }
        const abortController = new AbortController();
        this._abortSignal = abortController.signal;
        this.register(() => {
          abortController.abort();
        });
        await this.onloadComplete();
        this.app.workspace.onLayoutReady(this.onLayoutReady.bind(this));
      }
      /**
       * Saves the new plugin settings.
       *
       * @param newSettings - The new settings to save.
       * @returns A promise that resolves when the settings are saved.
       */
      async saveSettings(newSettings) {
        const json = newSettings.toJSON();
        this._settings = this.createPluginSettings(json);
        await this.saveData(json);
      }
      /**
       * Called when the layout is ready. This method can be overridden by subclasses to perform actions once
       * the layout is ready.
       *
       * @returns A promise or void indicating the completion of the layout setup.
       */
      onLayoutReady() {
        (0, import_Function.noop)();
      }
      /**
       * Called when the plugin loading is complete. This method must be implemented by subclasses to perform
       * any additional setup required after loading is complete.
       *
       * @returns A promise or void indicating the completion of the load process.
       */
      onloadComplete() {
        (0, import_Function.noop)();
      }
      /**
       * Displays a notice message to the user.
       *
       * @param message - The message to display.
       */
      showNotice(message) {
        if (this.notice) {
          this.notice.hide();
        }
        this.notice = new import_obsidian3.Notice(`${this.manifest.name}
${message}`);
      }
      /**
       * Loads the plugin settings from the saved data.
       *
       * @returns A promise that resolves when the settings are loaded.
       */
      async loadSettings() {
        const data = await this.loadData();
        this._settings = this.createPluginSettings(data);
        if (this._settings.shouldSaveAfterLoad()) {
          await this.saveSettings(this._settings);
        }
      }
    };
  }
});

// node_modules/obsidian-dev-utils/dist/lib/obsidian/Plugin/PluginSettingsBase.cjs
var require_PluginSettingsBase = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/obsidian/Plugin/PluginSettingsBase.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var PluginSettingsBase_exports = {};
    __export2(PluginSettingsBase_exports, {
      PluginSettingsBase: () => PluginSettingsBase2
    });
    module2.exports = __toCommonJS2(PluginSettingsBase_exports);
    var PluginSettingsBase2 = class {
      /**
       * Initializes the settings from JSON data.
       *
       * @param data - The data to initialize the settings from.
       */
      init(data) {
        if (data === void 0 || data === null) {
          return;
        }
        if (typeof data !== "object" || Array.isArray(data)) {
          const type = Array.isArray(data) ? "Array" : typeof data;
          console.error(`Invalid data type. Expected Object, got: ${type}`);
          return;
        }
        this.initFromRecord(data);
      }
      /**
       * Determines if the settings should be saved after loading.
       *
       * @returns A boolean indicating whether the settings should be saved after loading.
       */
      shouldSaveAfterLoad() {
        return false;
      }
      /**
       * Converts the settings to a JSON object.
       *
       * @returns The settings as a JSON object.
       */
      toJSON() {
        return Object.fromEntries(Object.entries(this));
      }
      initFromRecord(record) {
        for (const [key, value] of Object.entries(record)) {
          if (key in this) {
            this[key] = value;
          } else {
            console.error(`Unknown property: ${key}`);
          }
        }
      }
    };
  }
});

// node_modules/obsidian-dev-utils/dist/lib/obsidian/Plugin/PluginSettingsTabBase.cjs
var require_PluginSettingsTabBase = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/obsidian/Plugin/PluginSettingsTabBase.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var PluginSettingsTabBase_exports = {};
    __export2(PluginSettingsTabBase_exports, {
      PluginSettingsTabBase: () => PluginSettingsTabBase2
    });
    module2.exports = __toCommonJS2(PluginSettingsTabBase_exports);
    var import_obsidian3 = require("obsidian");
    var import_PluginBase2 = require_PluginBase();
    var PluginSettingsTabBase2 = class extends import_obsidian3.PluginSettingTab {
      constructor(plugin) {
        super(plugin.app, plugin);
        this.plugin = plugin;
      }
    };
  }
});

// node_modules/obsidian-dev-utils/dist/lib/Object.cjs
var require_Object = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/Object.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var Object_exports = {};
    __export2(Object_exports, {
      assignWithNonEnumerableProperties: () => assignWithNonEnumerableProperties,
      cloneWithNonEnumerableProperties: () => cloneWithNonEnumerableProperties,
      deepEqual: () => deepEqual,
      getNestedPropertyValue: () => getNestedPropertyValue,
      getPrototypeOf: () => getPrototypeOf,
      nameof: () => nameof,
      normalizeOptionalProperties: () => normalizeOptionalProperties,
      setNestedPropertyValue: () => setNestedPropertyValue,
      toJson: () => toJson
    });
    module2.exports = __toCommonJS2(Object_exports);
    var import_Error = require_Error();
    var __process = globalThis["process"] ?? {
      "cwd": () => "/",
      "env": {},
      "platform": "android"
    };
    function assignWithNonEnumerableProperties(target, ...sources) {
      return _assignWithNonEnumerableProperties(target, ...sources);
    }
    function cloneWithNonEnumerableProperties(obj) {
      return Object.create(getPrototypeOf(obj), Object.getOwnPropertyDescriptors(obj));
    }
    function deepEqual(a, b) {
      if (a === b) {
        return true;
      }
      if (typeof a !== "object" || typeof b !== "object" || a === null || b === null) {
        return false;
      }
      const keysA = Object.keys(a);
      const keysB = Object.keys(b);
      if (keysA.length !== keysB.length) {
        return false;
      }
      const aRecord = a;
      const bRecord = b;
      for (const key of keysA) {
        if (!keysB.includes(key) || !deepEqual(aRecord[key], bRecord[key])) {
          return false;
        }
      }
      return true;
    }
    function getNestedPropertyValue(obj, path) {
      let node = obj;
      const keys = path.split(".");
      for (const key of keys) {
        if (node === void 0) {
          return void 0;
        }
        node = node[key];
      }
      return node;
    }
    function getPrototypeOf(instance) {
      if (instance === void 0 || instance === null) {
        return instance;
      }
      return Object.getPrototypeOf(instance);
    }
    function nameof(name) {
      return name;
    }
    function normalizeOptionalProperties(obj) {
      return obj;
    }
    function setNestedPropertyValue(obj, path, value) {
      const error = new Error(`Property path ${path} not found`);
      let node = obj;
      const keys = path.split(".");
      for (const key of keys.slice(0, -1)) {
        if (node === void 0) {
          throw error;
        }
        node = node[key];
      }
      const lastKey = keys.at(-1);
      if (node === void 0 || lastKey === void 0) {
        throw error;
      }
      node[lastKey] = value;
    }
    function toJson(value, options = {}) {
      const {
        shouldHandleFunctions = false,
        space = 2
      } = options;
      if (!shouldHandleFunctions) {
        return JSON.stringify(value, null, space);
      }
      const functionTexts = [];
      const replacer = (_, value2) => {
        if (typeof value2 === "function") {
          const index = functionTexts.length;
          functionTexts.push(value2.toString());
          return `__FUNCTION_${index.toString()}`;
        }
        return value2;
      };
      let json = JSON.stringify(value, replacer, space);
      json = json.replaceAll(/"__FUNCTION_(\d+)"/g, (_, indexStr) => functionTexts[parseInt(indexStr)] ?? (0, import_Error.throwExpression)(new Error(`Function with index ${indexStr} not found`)));
      return json;
    }
    function _assignWithNonEnumerableProperties(target, ...sources) {
      for (const source of sources) {
        Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
      }
      const sourcePrototypes = sources.map((source) => getPrototypeOf(source)).filter((proto) => !!proto);
      if (sourcePrototypes.length > 0) {
        const targetPrototype = _assignWithNonEnumerableProperties({}, getPrototypeOf(target), ...sourcePrototypes);
        Object.setPrototypeOf(target, targetPrototype);
      }
      return target;
    }
  }
});

// node_modules/obsidian-dev-utils/dist/lib/obsidian/Plugin/ValueComponent.cjs
var require_ValueComponent = __commonJS({
  "node_modules/obsidian-dev-utils/dist/lib/obsidian/Plugin/ValueComponent.cjs"(exports2, module2) {
    function __extractDefault(module22) {
      return module22 && module22.__esModule && module22.default ? module22.default : module22;
    }
    (function patchRequireEsmDefault() {
      const __require = require;
      require = Object.assign((id) => {
        const module22 = __require(id) ?? {};
        return __extractDefault(module22);
      }, __require);
    })();
    var __defProp2 = Object.defineProperty;
    var __getOwnPropDesc2 = Object.getOwnPropertyDescriptor;
    var __getOwnPropNames2 = Object.getOwnPropertyNames;
    var __hasOwnProp2 = Object.prototype.hasOwnProperty;
    var __export2 = (target, all) => {
      for (var name in all)
        __defProp2(target, name, { get: all[name], enumerable: true });
    };
    var __copyProps2 = (to, from, except, desc) => {
      if (from && typeof from === "object" || typeof from === "function") {
        for (let key of __getOwnPropNames2(from))
          if (!__hasOwnProp2.call(to, key) && key !== except)
            __defProp2(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc2(from, key)) || desc.enumerable });
      }
      return to;
    };
    var __toCommonJS2 = (mod) => __copyProps2(__defProp2({}, "__esModule", { value: true }), mod);
    var ValueComponent_exports = {};
    __export2(ValueComponent_exports, {
      extend: () => extend2
    });
    module2.exports = __toCommonJS2(ValueComponent_exports);
    var import_obsidian3 = require("obsidian");
    var import_Object = require_Object();
    var ValueComponentEx = class {
      constructor(valueComponent) {
        this.valueComponent = valueComponent;
      }
      /**
       * Returns the ValueComponent with extended functionality.
       */
      asExtended() {
        return (0, import_Object.assignWithNonEnumerableProperties)({}, this.valueComponent, this);
      }
      /**
       * Binds the ValueComponent to a property in the plugin settings.
       *
       * @typeParam Plugin - The type of the plugin that extends `PluginBase`.
       * @typeParam Property - The key of the plugin setting that the component is bound to.
       * @typeParam PluginSettings - The type of the plugin settings object.
       * @param plugin - The plugin.
       * @param property - The property key in `PluginSettings` to bind to the UI component.
       * @param options - Configuration options.
       * @returns The `ValueComponent` instance that was bound to the property.
       */
      bind(plugin, property, options) {
        const DEFAULT_OPTIONS = {
          componentToPluginSettingsValueConverter: (value) => value,
          pluginSettingsToComponentValueConverter: (value) => value,
          shouldAutoSave: true
        };
        const optionsExt = { ...DEFAULT_OPTIONS, ...options };
        const pluginExt = plugin;
        const pluginSettingsFn = () => optionsExt.pluginSettings ?? pluginExt.settingsCopy;
        const validate = (uiValue) => {
          if (!optionsExt.valueValidator) {
            return true;
          }
          uiValue ??= this.valueComponent.getValue();
          const errorMessage = optionsExt.valueValidator(uiValue);
          const validatorElement2 = getValidatorElement(this.valueComponent);
          if (validatorElement2) {
            validatorElement2.setCustomValidity(errorMessage ?? "");
            validatorElement2.reportValidity();
          }
          return !errorMessage;
        };
        this.valueComponent.setValue(optionsExt.pluginSettingsToComponentValueConverter(pluginSettingsFn()[property])).onChange(async (uiValue) => {
          if (!validate(uiValue)) {
            return;
          }
          const pluginSettings = pluginSettingsFn();
          pluginSettings[property] = optionsExt.componentToPluginSettingsValueConverter(uiValue);
          if (optionsExt.shouldAutoSave) {
            await pluginExt.saveSettings(pluginSettings);
          }
          await optionsExt.onChanged?.();
        });
        validate();
        const validatorElement = getValidatorElement(this.valueComponent);
        if (validatorElement) {
          validatorElement.addEventListener("focus", () => validate());
          validatorElement.addEventListener("blur", () => validate());
        }
        return this.asExtended();
      }
    };
    function extend2(valueComponent) {
      return new ValueComponentEx(valueComponent).asExtended();
    }
    function getValidatorElement(valueComponent) {
      if (valueComponent instanceof import_obsidian3.DropdownComponent) {
        return valueComponent.selectEl;
      }
      if (valueComponent instanceof import_obsidian3.SliderComponent) {
        return valueComponent.sliderEl;
      }
      if (valueComponent instanceof import_obsidian3.TextAreaComponent) {
        return valueComponent.inputEl;
      }
      if (valueComponent instanceof import_obsidian3.TextComponent) {
        return valueComponent.inputEl;
      }
      return null;
    }
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);

// src/RefreshPreviewPlugin.ts
var import_obsidian2 = require("obsidian");
var import_Async = __toESM(require_Async(), 1);
var import_FileSystem = __toESM(require_FileSystem(), 1);
var import_PluginBase = __toESM(require_PluginBase(), 1);

// src/RefreshPreviewPluginSettings.ts
var import_PluginSettingsBase = __toESM(require_PluginSettingsBase(), 1);
var RefreshPreviewPluginSettings = class extends import_PluginSettingsBase.PluginSettingsBase {
  autoRefreshIntervalInSeconds = 0;
  autoRefreshOnFileChange = false;
  constructor(data) {
    super();
    this.init(data);
  }
};

// src/RefreshPreviewPluginSettingsTab.ts
var import_obsidian = require("obsidian");
var import_PluginSettingsTabBase = __toESM(require_PluginSettingsTabBase(), 1);
var import_ValueComponent = __toESM(require_ValueComponent(), 1);
var RefreshPreviewPluginSettingsTab = class extends import_PluginSettingsTabBase.PluginSettingsTabBase {
  display() {
    this.containerEl.empty();
    new import_obsidian.Setting(this.containerEl).setName("Auto refresh on file change").addToggle((toggle) => (0, import_ValueComponent.extend)(toggle).bind(this.plugin, "autoRefreshOnFileChange"));
    new import_obsidian.Setting(this.containerEl).setName("Auto refresh interval (seconds)").setDesc("Set to 0 to disable auto refresh").addText((text) => {
      (0, import_ValueComponent.extend)(text).bind(this.plugin, "autoRefreshIntervalInSeconds", {
        componentToPluginSettingsValueConverter: (uiValue) => parseInt(uiValue, 10),
        pluginSettingsToComponentValueConverter: (pluginSettingsValue) => pluginSettingsValue.toString(),
        valueValidator() {
          if (isNaN(text.inputEl.valueAsNumber)) {
            return "Please enter a numeric value";
          }
          if (text.inputEl.valueAsNumber < 0) {
            return "Value cannot be negative";
          }
          return null;
        }
      });
      text.inputEl.type = "number";
      text.inputEl.min = "0";
    });
  }
};

// src/RefreshPreviewPlugin.ts
var RefreshPreviewPlugin = class extends import_PluginBase.PluginBase {
  autoRefreshIntervalId = null;
  async saveSettings(newSettings) {
    await super.saveSettings(newSettings);
    this.registerAutoRefreshTimer();
  }
  createPluginSettings(data) {
    return new RefreshPreviewPluginSettings(data);
  }
  createPluginSettingsTab() {
    return new RefreshPreviewPluginSettingsTab(this);
  }
  onLayoutReady() {
    this.addRefreshPreviewButton();
    this.registerAutoRefreshTimer();
  }
  onloadComplete() {
    this.addCommand({
      checkCallback: this.refreshPreview.bind(this),
      id: "refresh-preview",
      name: "Refresh"
    });
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.addRefreshPreviewButton();
      })
    );
    this.registerDomEvent(document, "click", (event) => {
      if (event.target instanceof HTMLElement && event.target.matches(".refresh-preview-button")) {
        this.refreshPreview();
      }
    });
    this.register(() => {
      (0, import_Async.invokeAsyncSafely)(() => this.removeRefreshPreviewButton());
    });
    this.registerEvent(this.app.vault.on("modify", this.handleModify.bind(this)));
  }
  addRefreshPreviewButton() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (!view) {
      return;
    }
    if (view.getMode() !== "preview") {
      this.removeRefreshPreviewButtonFromView(view);
      return;
    }
    const actionsContainer = this.getActionsContainer(view);
    if (!actionsContainer) {
      return;
    }
    let refreshPreviewButton = this.getRefreshPreviewButton(actionsContainer);
    if (refreshPreviewButton) {
      return;
    }
    refreshPreviewButton = createEl("button", {
      cls: "refresh-preview-button clickable-icon view-action"
    });
    (0, import_obsidian2.setIcon)(refreshPreviewButton, "refresh-cw");
    (0, import_obsidian2.setTooltip)(refreshPreviewButton, "Refresh preview");
    actionsContainer.prepend(refreshPreviewButton);
  }
  getActionsContainer(view) {
    return view.containerEl.querySelector(".view-header .view-actions");
  }
  getRefreshPreviewButton(actionsContainer) {
    return actionsContainer.querySelector(".refresh-preview-button");
  }
  handleModify(file) {
    if (!this.settings.autoRefreshOnFileChange) {
      return;
    }
    if (!(0, import_FileSystem.isFile)(file)) {
      return;
    }
    if (!(0, import_FileSystem.isMarkdownFile)(this.app, file)) {
      return;
    }
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      if (leaf.view instanceof import_obsidian2.MarkdownView && leaf.view.file?.path === file.path) {
        this.refreshPreview(false, leaf.view);
      }
    }
  }
  refreshPreview(checking = false, view) {
    if (!view) {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
      if (!activeView) {
        return false;
      }
      view = activeView;
    }
    if (view.getMode() !== "preview") {
      return false;
    }
    if (!checking) {
      view.previewMode.rerender(true);
    }
    return true;
  }
  registerAutoRefreshTimer() {
    if (this.autoRefreshIntervalId) {
      clearInterval(this.autoRefreshIntervalId);
      this.autoRefreshIntervalId = null;
    }
    if (this.settings.autoRefreshIntervalInSeconds === 0) {
      return;
    }
    this.autoRefreshIntervalId = window.setInterval(() => {
      this.refreshPreview(false);
    }, this.settings.autoRefreshIntervalInSeconds * 1e3);
    this.registerInterval(this.autoRefreshIntervalId);
  }
  async removeRefreshPreviewButton() {
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      await leaf.loadIfDeferred();
      this.removeRefreshPreviewButtonFromView(leaf.view);
    }
  }
  removeRefreshPreviewButtonFromView(view) {
    const actionsContainer = this.getActionsContainer(view);
    if (!actionsContainer) {
      return;
    }
    const refreshPreviewButton = this.getRefreshPreviewButton(actionsContainer);
    if (refreshPreviewButton) {
      actionsContainer.removeChild(refreshPreviewButton);
    }
  }
};

// src/main.ts
var main_default = RefreshPreviewPlugin;

/* nosourcemap */